services:
  - type: web
    name: taskmanager-api
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: '60'

databases:
  - name: taskmanager-db
    region: frankfurt
    plan: free
